package wasi:random@0.2.0;
/// insecure接口用于不安全的伪随机数。
///
/// 它旨在至少在Unix系列平台和Windows之间具有可移植性。
interface insecure {
    /// 返回长度为`len`的不安全伪随机字节。
    ///
    /// 此函数不具备密码安全性。
    /// 请勿将其用于任何安全相关事项。
    ///
    /// 返回的字节的值没有具体的要求，
    /// 但是建议实现应返回均匀分布且具有长周期的值。
    get-insecure-random-bytes: func(len: u64) -> list<u8>;

    /// 返回不安全伪随机的`u64`值。
    ///
    /// 此函数返回与`get-insecure-random-bytes`相同类型的数据，表示为`u64`。
    get-insecure-random-u64: func() -> u64;
}
