package wasi:random@0.2.0;
/// insecure-seed接口用于播种(seeding)哈希映射(hash-map)DoS抵御(resistance)。
///
/// 它旨在至少在Unix系列平台和Windows之间具有可移植性。
interface insecure-seed {
    /// 返回可能包含伪随机值的128位值。
    ///
    /// 返回的值不要求由CSPRNG计算，并且甚至可以是完全确定性的。
    /// 鼓励宿主实现为任何暴露给攻击者已控内容(attacker-controlled content)的程序提供伪随机值，
    /// 以启用许多语言哈希映射实现中的DoS防护。
    ///
    /// 这个函数预期只被调用一次，由源语言来初始化其哈希映射实现中的服务拒绝(Denial Of Service，DoS)保护。
    ///
    /// # 预计的未来演变
    ///
    /// 这可能会被改变为一个值导入，以防止它被多次调用，并且可能被用于除了DoS保护之外的目的。
    insecure-seed: func() -> tuple<u64, u64>;
}
