package wasi:random@0.2.0;
/// WASI Random是随机数据API。
///
/// 它旨在至少在Unix系列平台和Windows之间具有可移植性。
interface random {
    /// 返回长度为`len`的密码安全随机(cryptographically-secure random)或伪随机(pseudo-random)字节。
    ///
    /// 此函数必须生成至少与足够种子的密码安全伪随机数生成器（CSPRNG）一样的密码安全且快速的数据。
    /// 从调用程序的视角看，在任何情况下它都不能阻塞，包括第一次请求和请求字节数时。
    /// 返回的数据必须始终是不可预测的。
    ///
    /// 这个函数必须始终返回最新数据。
    /// 确定性环境必须省略此函数，而不是使用确定性数据实现它。
    get-random-bytes: func(len: u64) -> list<u8>;

    /// 返回密码安全随机或伪随机的`u64`值。
    ///
    /// 此函数返回与`get-random-bytes`相同类型的数据，表示为`u64`。
    get-random-u64: func() -> u64;
}
